#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["BeamingInventory.Example.Presentation.App/BeamingInventory.Example.Presentation.App.csproj", "BeamingInventory.Example.Presentation.App/"]
COPY ["BeamingInventory.Example.Presentation.Entities/BeamingInventory.Example.Presentation.Entities.csproj", "BeamingInventory.Example.Presentation.Entities/"]
RUN dotnet restore "BeamingInventory.Example.Presentation.App/BeamingInventory.Example.Presentation.App.csproj"
COPY . .
WORKDIR "/src/BeamingInventory.Example.Presentation.App"
RUN dotnet build "BeamingInventory.Example.Presentation.App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BeamingInventory.Example.Presentation.App.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BeamingInventory.Example.Presentation.App.dll"]